### PR TITLE
Synchronize numbers in Achievements and Added Back To Top Button . Assigned #120 and #128

### PR DESCRIPTION
**Pull request by ishita80**
A back to top button with style similar to the website.

### CODE REVIEW

**Comment by ishita80** [comment]
1) In this second commit, I have synchronized the animated numbers in achievements section (which were asynchronized earlier). 
2) I have also added a "+" sign with the numbers. (except when it is 0)

**Comment by aniketsinha2002** [comment]
@ishita80 Resolve merge conflicts !!

**Comment by ishita80** [comment]
Sir, I have removed many things but conflicts are still not resolving. Many lines of code have been removed but those lines still  showing in conflicts. Please guide me.

**Comment by ishita80** [comment]
It is also showing conflict in popular courses in style.css despite the fact that I have not even worked on it

**Comment by ishita80** [comment]
Same goes with faqs

**Pull request closed without merging**
