### PR TITLE
Added Contributers List to the website

### PR DESCRIPTION
**Pull request by Sch476**
# Description

Added the Contributor List.

## Fixes #(issue_no)

Fixed the issue #724 . 

## Screenshots

Video : 

https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/127319225/154163a2-d5ff-4827-ab0a-8607c6c271a8

Just a small request, please consider this issue to be of level 3 . It will help me very much.

Thank You

## Checklist

- [ x] Tests have been added or updated to cover the changes
- [ x] Documentation has been updated to reflect the changes
- [ x] Code follows the established coding style guidelines
- [x ] All tests are passing

### CODE REVIEW

**Comment by aniketsinha2002** [comment]
@Sch476 The image size is very large. Make them smaller in size at least 1/4th of what you've given now!

**Comment by Sch476** [comment]
Then can I change the styles of this page as a whole, I will make it smaller and will make sure to make it a bit smaller.

**Comment by aniketsinha2002** [comment]
@Sch476 The theme, colors, background, and fonts of the page must remain the same!!

**Comment by Sch476** [comment]
Changed : 

https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/127319225/ac83a279-fa3b-413d-b330-a6652d9fcf52

**Comment by Sch476** [comment]
@aniketsinha2002 Made the changes as you said

**Pull request merged**
