### PR TITLE
Changes in Dark mode and Light mode

### PR DESCRIPTION
**Pull request by Ankittap2001**
adding me in the contribute list

### CODE REVIEW

**Comment by aniketsinha2002** [comment]
@Ankittap2001 Correct the title into the specific changes you've made

**Comment by Ankittap2001** [comment]
I can't understand will u tell me in details plz

**Comment by aniketsinha2002** [comment]
@Ankittap2001 What changes you've made or worked on?

**Comment by Ankittap2001** [comment]
i added root and darktheme class file in css in html i added 1script file at the end to add dark mode and light mode

**Comment by aniketsinha2002** [comment]
@Ankittap2001 Please resolve merge conflicts !

**Comment by Ankittap2001** [comment]
done

**Pull request merged**
