### PR TITLE
Added a new doubt section and made minor social network placement

### PR DESCRIPTION
**Pull request by Krishi1211**
As mentioned in the issue #14  I have added a doubt section and also changed the position of flying social media accounts

### CODE REVIEW

**Review by Krishi1211 — COMMENTED** [review]
This is a great change as a new section named doubts was added with html,css,javascript

**Comment by aniketsinha2002** [comment]
@Krishi1211 Kindly resolve merge conflicts !!

**Comment by Krishi1211** [comment]
> @Krishi1211 Kindly resolve merge conflicts !!

done

**Comment by aniketsinha2002** [comment]
Still there are merge conflicts !!

**Comment by Krishi1211** [comment]
> Still there are merge conflicts !!

Please check now
image

**Comment by Krishi1211** [comment]
> Still there are merge conflicts !!

@aniketsinha2002 try now

**Comment by Rajatkumarbehera11** [comment]
login changed

**Pull request merged**
