### PR TITLE
smooth navigation

### PR DESCRIPTION
**Pull request by nishita2104**

### CODE REVIEW

**Comment by nishita2104** [comment]
I have made the navigation smooth by adding scroll-behaviour and a scroll margin in the css file.

**Comment by aniketsinha2002** [comment]
@nishita2104 Resolve merge conflicts!

**Comment by nishita2104** [comment]
merge conflicts resolved.

**Comment by nishita2104** [comment]
@aniketsinha2002 I request you to add labels to this PR. This solves the issue #16

**Pull request merged**
