### PR TITLE
Issue #703 fixed 

### LINKED ISSUE #703: The site is not responsive At all
### Description

I visited you site and found that the site is not responsive at different screen size.

I have provided the screenshot for the same issue .

I can make it responsive pls assign it to me 

### Screenshots

Screenshot 2023-07-31 155102
Screenshot 2023-07-31 155127

### PR DESCRIPTION
**Pull request by adityakmrmishra**
# Description

I have added a media query css file and made some changes in inline css . 

## LAPTOP
Screenshot 2023-08-04 183739
## TABLET
Screenshot 2023-08-04 183801
## MOBILE
Screenshot 2023-08-04 183840

##Working video 

https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/105539123/6fafcac3-bc05-4723-b3fe-d682fea846dc

## THANK YOU  FOR ASSIGNING THIS TO ME

### CODE REVIEW

**Comment by Adityamishra9719** [comment]
THESE ARE THE FILE WHICH ARE CHANGED 

image

**Comment by Adityamishra9719** [comment]
@aniketsinha2002 pls review and merge this pr

**Comment by adityakmrmishra** [comment]
> @aniketsinha2002 pls review and merge this pr 

Pls merge it

**Comment by aniketsinha2002** [comment]
@adityakmrmishra Please resolve the merge conflicts !!

**Comment by adityakmrmishra** [comment]
> @adityakmrmishra Please resolve the merge conflicts !!

done

**Pull request merged**
