### PR TITLE
Added `Chat bot`

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Hello @aniketsinha2002, 
I have added the `chat-bot` please review it.

### Screenshots - 
Screenshot from 2023-05-25 11-01-25

Screenshot from 2023-05-25 11-01-36

### Video -
[Screencast from 25-05-23 11:02:09 AM IST.webm](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/121503426/e274ef6e-20ee-4776-bb96-0345cf0e3b82)

### It is ready to `Merge` 👍🏻

### CODE REVIEW

**Comment by aniketsinha2002** [comment]
@SyedImtiyaz-1 Wonderful work !! Please resolve merge conflicts !!

**Comment by SyedImtiyaz-1** [comment]
sure sir @aniketsinha2002

**Comment by SyedImtiyaz-1** [comment]
Hello @aniketsinha2002,
Conflicts resolved you can merge this now.

**Comment by SyedImtiyaz-1** [comment]
Hey @aniketsinha2002 must review the `Chat Bot` I think it's seems interesting for you. 💯

**Comment by aniketsinha2002** [comment]
@SyedImtiyaz-1 again there are some merge conflicts

**Comment by SyedImtiyaz-1** [comment]
Got it resolving the conflicts **give me 2mins** 👍🏻

**Comment by SyedImtiyaz-1** [comment]
All Fix let's merge again 👍🏻 

Screenshot from 2023-05-26 00-45-51

**Comment by SyedImtiyaz-1** [comment]
Hello @aniketsinha2002 ,
there are few issues raising a PR with more optimize JavaScript code.

**Pull request closed without merging**
