### PR TITLE
fixed issue 43

### PR DESCRIPTION
**Pull request by bhavyanarnoli**
added vanilla tilt and made the buttons aligned with each other
image
vanilla tilt as shown in middle and rest are aligned as shown in picture
image

### CODE REVIEW

**Comment by bhavyanarnoli** [comment]
@aniketsinha2002 please look into this

**Comment by aniketsinha2002** [comment]
@bhavyanarnoli Resolve merge conflicts !!

**Comment by bhavyanarnoli** [comment]
wait ill fix and let you know

**Comment by bhavyanarnoli** [comment]
fixed them let me know if anything else still to improve @aniketsinha2002

**Comment by aniketsinha2002** [comment]
Wonderful work!! @bhavyanarnoli

**Pull request merged**
