### PR TITLE
[FEATURE] <description> #741 Resolved

### LINKED ISSUE #741: [FEATURE] <description>
### Description

Hey, I want to implement a chatbot feature in the website that will enhance the engagement with audiences and look appealing to the visitor. You can see the last section of the website does not looks appealing and it seems like it's there with no use. I am willing to implement this new feature. Kindly assign this to me under GSSOC'23.

### Screenshots

image

### PR DESCRIPTION
**Pull request by Manishak798**
I have implemented the chatbot successfully and it is looking appealing as a visitor.

# Description

I have implemented the chatbot in the website using HTML, CSS, and JavaScript.

## Fixes #741 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by Manishak798** [comment]
hey @aniketsinha2002 Kindly review my PR as only a few hours left for gssoc.

**Comment by Manishak798** [comment]
Before:

image

AFTER:
image

**Comment by Manishak798** [comment]
Hey @aniketsinha2002 let me know your views on the same.

**Comment by aniketsinha2002** [comment]
@Manishak798 Can you place it on the rightmost side of the window, not below the footer section? You can take the example of any website that has the same feature !!

**Comment by Manishak798** [comment]
> @Manishak798 Can you place it on the rightmost side of the window, not below the footer section? You can take the example of any website that has the same feature !!

Sure I will do that just give me some time and I will get back to you immediately.

**Comment by Manishak798** [comment]
Hey @aniketsinha2002 I have positioned the bot kindly view my PR.
image

**Comment by Manishak798** [comment]
Hey @aniketsinha2002 only 25min are left for GSSOC I request you to view my PR ASAP, I hope you understand my concern.

**Comment by Manishak798** [comment]
@aniketsinha2002 let me know your views on the same.

**Comment by Manishak798** [comment]
@aniketsinha2002 as only a few minutes left for gssoc to over I have putten my efforts kindly view my PR.

**Comment by Manishak798** [comment]
@aniketsinha2002 kindly view my PR.

**Comment by Manishak798** [comment]
@aniketsinha2002 please view my PR

**Comment by aniketsinha2002** [comment]
Good job @Manishak798 !!

**Comment by Manishak798** [comment]
I am very thankful to you @aniketsinha2002.

**Comment by Manishak798** [comment]
> Good job @Manishak798 !!

Thank you so much, Happy to connect with you.

**Pull request merged**
