### PR TITLE
(#30) Put all FAQ question-answers to an Array [GSSOC'23]

### LINKED ISSUE #30: Put all FAQ question-answers to an Array [GSSOC'23]
- Put all the FAQs in an Array, so that if a new faq is to be inserted, it can directly be pushed to the array.
- Will make the HTML file more readable
- Reduce these many lines
image

Please assign me this issue under GSSOC'23

### PR DESCRIPTION
**Pull request by kartikayasija**
closes #30 

- A new data file is created which contains an array of all question answers
- Code is now more readable
- Questions related to data science are added

image

### CODE REVIEW

**Comment by aniketsinha2002** [comment]
@kartikayasija Resolve merge conflicts !!

**Comment by kartikayasija** [comment]
@aniketsinha2002  Conflicts Resolved

**Comment by aniketsinha2002** [comment]
@kartikayasija  Still there are merge conflicts !!

**Comment by kartikayasija** [comment]
I had merged the conflicts previously , but after merging of a PR it had come again. Anyways, I have again resolved.

image

**Comment by kartikayasija** [comment]
Please add labels for Gssoc

**Pull request merged**
